stori:
  prod:
    functions:      
      stori-transformation:
        handler: src/functions/transformation.handler
        role: 'arn:aws:iam::${aws:accountId}:role/stori-data-service-role'
        name: 'stori-${opt:stage, ''prod''}-${self:service}-transformation'
        maximumRetryAttempts: 0
        timeout: 240
        memorySize: 256
        events:
          - s3:
              bucket: stori-data-services-in-prod
              event: s3:ObjectCreated:*
              rules:
                - prefix: images/
                - suffix: .jpg
              existing: true
        layers:
          - arn:aws:lambda:${aws:region}:${aws:accountId}:layer:stori-services-commons-lt:latest
          - arn:aws:lambda:us-east-1:594512103563:layer:AWSSDKPandas-Python38:1
