name: stori-infrastructure

on:
  workflow_dispatch:

env:
  REGION: us-east-1
  CAPABILITIES: CAPABILITY_NAMED_IAM
  BUCKET_CFG: stori-artifacts-prod

jobs:
  stori-s3-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      STAGE: prod
      SAM_TEMPLATE: cloudformation/s3/stori.yml
      AWS_ACCOUNT: ${{ secrets.AWS_STORI_ACCOUNT }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: "Set environment variables"
        run: |
          echo "PREFIX=sam-templates/$GITHUB_WORKFLOW" >> $GITHUB_ENV
      - name: Configure STORI AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_STORI_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_STORI_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
      - name: STORI SAM Setup
        uses: aws-actions/setup-sam@v2
      - name: STORI SAM Build
        run: |
          sam build -t $SAM_TEMPLATE --use-container
      - name: STORI SAM Deploy
        run: |
          sam deploy -t $SAM_TEMPLATE \
            --stack-name $GITHUB_WORKFLOW-s3-$STAGE \
            --capabilities $CAPABILITIES \
            --region $REGION \
            --parameter-overrides "Stage=$STAGE" \
            --s3-bucket $BUCKET_CFG \
            --s3-prefix $PREFIX \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --force-upload
  
  stori-iam-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      STAGE: prod
      SAM_TEMPLATE: cloudformation/iam/stori.yml
      AWS_ACCOUNT: ${{ secrets.AWS_STORI_ACCOUNT }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: "Set environment variables"
        run: |
          echo "PREFIX=sam-templates/$GITHUB_WORKFLOW" >> $GITHUB_ENV
      - name: Configure STORI AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_STORI_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_STORI_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
      - name: STORI SAM Setup
        uses: aws-actions/setup-sam@v2
      - name: STORI SAM Build
        run: |
          sam build -t $SAM_TEMPLATE --use-container
      - name: STORI SAM Deploy
        run: |
          sam deploy -t $SAM_TEMPLATE \
            --stack-name $GITHUB_WORKFLOW-iam-$STAGE \
            --capabilities $CAPABILITIES \
            --region $REGION \
            --parameter-overrides "Stage=$STAGE" \
            --s3-bucket $BUCKET_CFG \
            --s3-prefix $PREFIX \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --force-upload

  stori-lambda-prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - run: npm ci
      - name: Install Serverless Framework
        run: npm install -g serverless@3
      - name: Stori Authentication
        run: serverless config credentials --provider aws --key ${{secrets.AWS_STORI_DEPLOY_ACCESS_KEY_ID}} --secret ${{secrets.AWS_STORI_DEPLOY_SECRET_ACCESS_KEY}} -o
      - name: Stori Deploy
        run: |
          serverless plugin install --name serverless-python-requirements
          serverless plugin install --name serverless-latest-layer-version
          serverless plugin install --name serverless-disable-functions
          serverless deploy --stage prod --region us-east-1 --param="stack=Stori" --force --verbose --o